---
 - name: Transfer the kube config file to url
   when: inventory_hostname in groups['kube-master']
   shell: curl -i -X POST \
               -H "Content-Type= multipart/form-data" \
               -F "kube_config=@$HOME/.kube/config" \
                   {{ NEXA_IP }}/v1/kube_config
